### PR TITLE
Upgrade flow

### PR DESCRIPTION
**Pull request by joeybaker**
Latest React Native releases require Flow `0.47.` That version
catches issues that Flow `0.33` which this repo is locked to doesn't.
This PR upgrades Flow and fixes those issues.

### CODE REVIEW

**Comment by joeybaker** [comment]
Travis is failing because eslint can't find builtin flow types. I think you can fix this with https://www.npmjs.com/package/eslint-plugin-flowtype

**Comment by joeybaker** [comment]
Installed that plugin as a part of this PR.

**Comment by joeybaker** [comment]
Thanks! Any chance of an updated npm version?

**Comment by Swordsman-Inaction** [comment]
@joeybaker Will release a new version after most PRs are merged. Won't be long.

**Comment by alvaromb** [comment]
Released! https://github.com/APSL/react-native-keyboard-aware-scroll-view/releases/tag/v0.3.0

**Comment by alvaromb** [comment]
Sorry for the delay guys, tons of work ATM

**Pull request merged**
