### PR TITLE
Support non-zero y position for scroll/list views.

### PR DESCRIPTION
**Pull request by osadchuk**
If a scrollview is positioned underneath a component
that does not scroll, a focussed text input can still
end up hidden by the keyboard. Adding an amount to the
scroll equal to the y-position of the scroll view fixes
the problem.

### CODE REVIEW

**Comment by osadchuk** [comment]
- I'm not sure how `resetKeyboardSpace` isn't handled correctly, but if there's a use case I haven't accounted for let me know and I'd be happy to accommodate it. (We first encountered this issue in a reasonably complex app, but I was able to reproduce the issue from a brand new React Native project that imports only react-native-keyboard-aware-scroll-view, so as to eliminate other potential causes.)

- This could be made optional, although I'm not sure there are many situations where one would want the text input field hidden behind the keyboard.

- If `extraScrollHeight` is set to the value of `yOffset`, then when the keyboard is dismissed there's white space at the bottom of the scroll view, because the scroll view's content inset `bottom` value is equal to `keyboardSpace`, and `resetKeyboardSpace` sets `keyboardSpace` to the value of `extraScrollHeight`. This seems to happen whether the scroll view takes up the whole view or not. I can take another look but my setup of the test project seemed correct, etc.

**Comment by Swordsman-Inaction** [comment]
@osadchuk Sorry, I was wrong about the `resetKeyboardSpace` and `extraScrollHeight` thing, but I still don't think it should be the default behavior, since it will hide the component which is above of the `ScrollView` even the keyboard is not cover the `TextInput`.

**Comment by alvaromb** [comment]
Hi @osadchuk!

Let me check in a while your PR.

Thanks for contributing!

**Comment by osadchuk** [comment]
@Swordsman-Inaction It shouldn't hide the component above the scrollview, as the change only reads the scrollview's y-position and applies that amount to the scroll. It doesn't modify the styles, or layout of the scrollview or other components. This is the behaviour in both my simple test app and the app where we're using my PR branch at the moment; if you're seeing something different then let me know since that's definitely a bug.

I can add a flag to disable this behaviour - my preference would be for it to be the default behaviour but users could opt out of it. I can't think of a situation, offhand, where one would want the text input to be covered by the keyboard, so enabling this change by default would be simplest, but making it possible to disable would at least give developers the option to do so.

@alvaromb You're welcome!

**Comment by Swordsman-Inaction** [comment]
@alvaromb How do you think about this one?

**Comment by alvaromb** [comment]
@osadchuk can you solve the conflicts?

**Comment by osadchuk** [comment]
Hi, sorry for the delay in getting back to you; I believe the merge conflict is now fixed.

**Comment by alvaromb** [comment]
Can you solve the tests @osadchuk?

**Comment by Swordsman-Inaction** [comment]
Could you please do a `rebase`? The commit log is a mess now. Thanks. @osadchuk

**Comment by osadchuk** [comment]
Sure, I can take a look, but probably won't be for a couple of days, I'm afraid.

**Comment by osadchuk** [comment]
Quick update: I've rebased and I've fixed the failing test, but would like to test a bit more; unfortunately I'm on holiday as of tomorrow so I won't be able to take another look at this for a couple weeks. I'll update the PR when we get back and I've had some time to run through and make sure things are still working as expected.

**Comment by gontovnik** [comment]
Any update on this one?

**Comment by osadchuk** [comment]
Sorry, haven't had a chance to look into the failing tests issue, but will try to do so this week.

**Comment by osadchuk** [comment]
Hi, sorry for the delay. I actually just pulled the latest and it looks like the bug has been fixed already, so this PR isn't needed any more. Will close. Thanks!

**Pull request closed without merging**
