### PR TITLE
Add Android Support

### LINKED ISSUE #2: Android support?
Should this work for Android? I was having an issue with a view in iOS and Android and I put this component in place. It seemed to fix the iOS version, but the Android version still behaves the same (the keyboard covers the content in the ScrollView).

### PR DESCRIPTION
**Pull request by Swordsman-Inaction**
Hey!

We'll have Android Support now! You guys can check the README about this.

This feature is not perfect, since there is no `keyboardWillShow` on Android, we cannot be notified before the keyboard is showed. So sometimes we could get wrong position of focused TextInput because it's already in the process of showing keyboard which makes `keyboardSpace` not accurate occasionally.

Feel free to review the code and test on your app!

Fix #2

### CODE REVIEW

**Comment by Swordsman-Inaction** [comment]
@chirag04 @Palisand @Jose4gg @tizzyapunkt Would you like to test this feature? 😀

**Comment by Palisand** [comment]
@Swordsman-Inaction WIll do soon.

**Comment by Swordsman-Inaction** [comment]
@Palisand OK... I don't use `adjustResize` because this option will change the window size which makes positioning more difficult. Also this option doesn't have scroll animation.

**Comment by Palisand** [comment]
@Swordsman-Inaction With these changes, space gets added below the view holding the input, so it works just fine if I scroll manually. By the way, are there any plans for making the view scroll to the text input cursor (for multiline inputs) rather than the bottom of the input? I've tried to accomplish this myself, but found that RN doesn't expose the cursor's location.

**Comment by benhannel** [comment]
I used this as a drop in replacement for the APSL version for my project and it worked perfect. Thanks Swordsman-Inaction! When will this request get merged?

**Comment by Palisand** [comment]
@alvaromb ^

**Comment by Swordsman-Inaction** [comment]
@Palisand The first issue, `space gets added below the view`, is it been introduced in this PR? Is it related to #142?
About the second one, `scroll to the text input cursor`, as you mentioned RN doesn't expose the cursor's location, it might be impossible to do it. I haven't got time to do the research, I'll do it later, maybe try to work on the native level.

**Comment by Palisand** [comment]
@Swordsman-Inaction I've only compared APSL's master version and your forked repo's android-support branch and with the latter, space does get added below the view when I focus on the input. **I wasn't treating it as an issue** as I thought this was intentional.

From what I've learned, the second one appears possible only on the native level.

**Comment by Swordsman-Inaction** [comment]
@Palisand I see, you are saying `extraHeight` and `extraScrollHeight` works on Android now, right?

**Comment by Palisand** [comment]
@Swordsman-Inaction I never included nor tested those props, only `enableOnAndroid`. What I'm saying is that before your changes, I was unable to scroll (manually) to an input on Android when the keyboard was shown. Since I can now, I am assuming there is some space being added below the view holding the input.

**Comment by Swordsman-Inaction** [comment]
@Palisand Yes, that's right. 😀

**Comment by alvaromb** [comment]
@Swordsman-Inaction ping me when all the PRs are merged and I'll perform a release. Thanks for your work!

**Comment by nicotroia** [comment]
I've upgraded to react-native 0.46.+, changed my AndroidManifest file, and set `enableOnAndroid` to true, and still cannot get any extra padding via `extraHeight` or `extraScrollHeight`. Neither work for me

**Comment by alliecurry** [comment]
@nicotroia I don't believe there was a new release of this library, yet even though this is merged in.

**Comment by alvaromb** [comment]
I'm waiting for @Swordsman-Inaction confirmation to release 0.3.0.

**Comment by hose314** [comment]
@Swordsman-Inaction any updates?

**Comment by Swordsman-Inaction** [comment]
@hose314 Should be released soon, already confirmed with @alvaromb before. 😄

**Comment by alvaromb** [comment]
I can confirm it will be released tomorrow morning CEST.

Thanks!

**Pull request merged**
