### PR TITLE
added Android support for KeyboardAwareScrollView

### PR DESCRIPTION
**Pull request by jblack10101**
Only added support for KeyboardAwareScrollView so far.  It looks like ListView is implemented differently in React, and I will need to investigate a different type of solution.

### CODE REVIEW

**Comment by alvaromb** [comment]
Jesus! completely forgot to review this, I'm sorry @jblack10101 !

I'll test this this week and release `0.1.0` with it, ok? Thanks for your PR.

**Comment by jblack10101** [comment]
I've actually been on vacation for the past 2 weeks, so I wasn't able to respond to your message.  But yea, please review and merge when you can. Thanks

**Comment by anthonywebb** [comment]
Android support would be great

**Comment by skeie** [comment]
Whats the status of this PR? Would it be merged into master soon? :-)

**Comment by franzejr** [comment]
I would love to have this on master!

**Comment by sarovin** [comment]
@jblack10101 
Can you help me with this? => https://github.com/sarovin/react-native-scrollview-smart

**Comment by alvaromb** [comment]
Hi all!

Sorry for the delay about this topic. There's an updated PR for bringing support for the Keyboard handling into Android (see #29).

I'm ready to merge one solution or the other to bring support for this, however I would like somebody with Android experience to check #25 before merging. It is an important bug and needs changes into the upstream `react-native` repo. I come from the iOS world and I'm no Android expert, so any help would be much appreciated.

Thanks.

**Comment by alvaromb** [comment]
Closed in favor of #147

**Pull request closed without merging**
