### PR TITLE
WIP: HOC options API

### PR DESCRIPTION
**Pull request by slorber**
@alvaromb it's a work in progress, not to merge yet

if you have any opinion on this tell me please

### CODE REVIEW

**Comment by slorber** [comment]
hey @alvaromb , my code seems to work fine in my app

I am not able to merge my PR, not to push directly on master

**Comment by slorber** [comment]
@alvaromb can you give me the rights to merge and publish? Or approve the PR?

**Comment by alvaromb** [comment]
Sorry @slorber, please try again

**Comment by slorber** [comment]
thanks, this seems to be working now. I'll make a release with notes soon

**Pull request merged**
