### PR TITLE
currentlyFocusedField => currentlyFocusedInput

### PR DESCRIPTION
**Pull request by kangyunu**
currentlyFocusedField => currentlyFocusedInput

https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/440#issuecomment-671836481

### CODE REVIEW

**Comment by sclavijo93** [comment]
Any chance to merge this up? 😅  🙏

**Comment by ortonomy** [comment]
Is the new API in old versions of react? Would this need to be published as a new package version, and README also updated to let anyone know to use old version on older versions of native?

**Comment by Karthik-B-06** [comment]
Why hasn't this branch not merged yet ??

**Comment by beqaweb** [comment]
Could you please merge this? It's a simple fix, literally 2 lines of code modified.
Thanks in advance!

**Comment by ramazanarslan** [comment]
could you merge please 🚀

**Comment by rborn** [comment]
LGTM @alvaromb

**Review by Gaoey — APPROVED** [review]

**Review by german-schneck — APPROVED** [review]

**Review by tastafur — APPROVED** [review]

**Comment by rborn** [comment]
@alvaromb will merge, maybe we make a release to npm ? 😄

**Comment by PropeReferio** [comment]
I just installed this, and I'm still getting the "currentlyFocusedField is deprecated and will be removed in a future relase. Use currentlyFocusedInput" error

**Comment by rborn** [comment]
@PropeReferio did you install from git? is not pushed to npm as far as I know

**Comment by PropeReferio** [comment]
Ah, ok. No, I installed with yarn.

**Comment by Dallas62** [comment]
Hi @rborn 
Do you have some estimate for a release with this PR ?
Best regards,

**Comment by rborn** [comment]
cc: @Moreno97

**Comment by Moreno97** [comment]
Hello guys, I will release a new version ASAP :)

**Comment by Moreno97** [comment]
Published last version v0.9.3 to NPM @rborn @rkdqudtjs1

**Pull request merged**
