### PR TITLE
Migrating from React.PropTypes to prop-types to react-native v0.44

### PR DESCRIPTION
**Pull request by ozsirma**

### CODE REVIEW

**Comment by mmmurf** [comment]
+1

**Comment by mmmurf** [comment]
Please merge this one as it is blocking my update of react-native to the latest.

**Comment by Swordsman-Inaction** [comment]
Looks nice! Just one question: Is this change compatible with older react-native?

**Comment by ozsirma** [comment]
It is usable for after react 15.5

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by ozsirma** [comment]
@alvaromb Thank you for 0.3.0

**Pull request merged**
