### PR TITLE
Replaced React.createClass with createReactClass

### PR DESCRIPTION
**Pull request by iRoachie**
React.createClass is deprecated in react15.5 and throws errors. This PR replaces it with the drop in replacement create-react-class

### CODE REVIEW

**Comment by iRoachie** [comment]
Also fixes #140, there was a stray React.PropTypes still remaining.

**Comment by cladjules** [comment]
Hi iRoachie, thanks for the fix,

when can we have that in the master?
So we can start using it.

Thanks :)

**Comment by iRoachie** [comment]
Currently waiting on merge. @Swordsman-Inaction

**Comment by itsmepetrov** [comment]
@Swordsman-Inaction please, push the new version to` npm`

**Comment by Swordsman-Inaction** [comment]
@alvaromb Can you do it?

@itsmepetrov Sorry, I don't have the permission to push a new version. But you can use `github:APSL/react-native-keyboard-aware-scroll-view#commit-id` to use this commit before it's pushed.

**Comment by iRoachie** [comment]
`"react-native-keyboard-aware-scroll-view": "https://github.com/APSL/react-native-keyboard-aware-scroll-view.git"`

**Comment by alvaromb** [comment]
Sorry for the delay, I'm publishing it today!

**Comment by itsmepetrov** [comment]
@alvaromb any updates?

**Comment by isnifer** [comment]
@alvaromb please update module on npm

**Pull request merged**
