### PR TITLE
change deviceEventEmitter to Keyboard for rn 0.27.2

### PR DESCRIPTION
**Pull request by evollu**
fix for issue #30

### CODE REVIEW

**Comment by alvaromb** [comment]
Hi @evollu and thanks for the PR!

What's the backward compatibility policy for this PR? Would this work under RN 0.26 and older?

**Comment by evollu** [comment]
It won't be compatible with older version. Is that required?

**Comment by wrousseau** [comment]
+1, it's a deprecation on react native. Here are the changes listed on react native changelog

```
// previously
const { DeviceEventEmitter } = require('react-native');
DeviceEventEmitter.addListener('keyboardWillShow', func);

// on 0.27.2 and newer
const { Keyboard } = require('react-native');
Keyboard.addListener('keyboardWillShow', func);

// 0.27.0 & 0.27.1
const Keyboard = require('Keyboard');
Keyboard.addListener('keyboardWillShow', func);
```

**Comment by alvaromb** [comment]
Cool!

Can you update the `README` to reflect the compatibility @evollu? Something like 
> 0.1.2 requires RN>=0.27.2

**Comment by evollu** [comment]
@alvaromb readme updated

**Comment by grabcode** [comment]
+1

**Comment by alvaromb** [comment]
Merged! Will release today. Many thanks!

**Comment by alvaromb** [comment]
Released https://github.com/APSL/react-native-keyboard-aware-scroll-view/releases/tag/v0.1.2

**Comment by ms88privat** [comment]
@alvaromb run into this today with RN 0.26. Could you please bump the Version Number in a Major style, e.g. v0.2.0? Other Apps will break...

**Pull request merged**
