### PR TITLE
fix RN 0.65 crash

### PR DESCRIPTION
**Pull request by oliverdolgener**

### CODE REVIEW

**Comment by garydevenay** [comment]
Can confirm that this fixes my crash issue on 0.65.1

**Comment by mingtsay** [comment]
Tried install using:
`npm install --save  APSL/react-native-keyboard-aware-scroll-view#pull/501/head` or
`yarn add APSL/react-native-keyboard-aware-scroll-view#pull/501/head`
It works!

This will change your dependency in package.json to:
`"react-native-keyboard-aware-scroll-view": "APSL/react-native-keyboard-aware-scroll-view#pull/501/head",`

**Review by nagarajbalan — APPROVED** [review]

**Comment by HZHAIX** [comment]
Would be good to have this merged, looks just api changed and all approved.
Looking forward to see this include this include in the next release

**Comment by dongdyang** [comment]
@oliverdolgener please help to merge. Thanks!

**Comment by AndyShi12** [comment]
Getting a similar crash even with the `scrollTo` change
- `react-native: "0.65.1"`
- `react: "17.0.2"`
- metro cache reset

Screen Shot 2021-09-07 at 5 16 30 PM

**Comment by mlazari** [comment]
I am seeing this crash only in iOS simulator, works fine on my iPhone. With this change it works on both.

**Comment by mingtsay** [comment]
> I am seeing this crash only in iOS simulator, works fine on my iPhone. With this change it works on both.

It crashes on both simulator and physical devices for me.
(perhaps your device has js bundle shipped while building and not updated? I duno.)
But this PR certainly fixes that.

**Comment by kkkorez** [comment]
Please merge @oliverdolgener

**Comment by mlazari** [comment]
@mingtsay 

> > I am seeing this crash only in iOS simulator, works fine on my iPhone. With this change it works on both.
> 
> It crashes on both simulator and physical devices for me.
> (perhaps your device has js bundle shipped while building and not updated? I duno.)
> But this PR certainly fixes that.

Yes, you're right. I double checked and it happens on both. The difference is that my real device is iPhone SE 2020 and the iOS simulator I was using was iPhone 12 Pro Max. On SE the error occurs for me when the keyboard is dismissed, while on 12 Pro Max - when it opens. Probably it's because of different screen size or something.

**Comment by oliverdolgener** [comment]
> Please merge @oliverdolgener 

I wish I could but I'm just a user like you guys :(

**Comment by eliw00d** [comment]
@slorber Are you able to approve, merge, and increment the npm version?

**Comment by mingtsay** [comment]
I go read the source code of React Native 0.48 branch and see this line:
https://github.com/facebook/react-native/blob/6ce42441ec98bb8543e8eff8849ce50e076ce520/Libraries/Components/ScrollView/ScrollView.js#L493
So I can confirm that this change will work from 0.48 to 0.65, and also 0.66 (next).

`scrollResponderScrollTo` is gone because the file `ScrollResponder.js` in `react-native/Libraries/Components/` is removed from branch of 0.65.

Feel free to try this PR in React Native 0.48 to latest version to make sure whether it works or not if you like to.

**Comment by kutaisan** [comment]
> Tried install using:
> `npm install --save APSL/react-native-keyboard-aware-scroll-view#pull/501/head` or
> `yarn add APSL/react-native-keyboard-aware-scroll-view#pull/501/head`
> It works!
> 
> This will change your dependency in package.json to:
> 
> ```diff
> - "react-native-keyboard-aware-scroll-view": "^0.9.4",
> + "react-native-keyboard-aware-scroll-view": "APSL/react-native-keyboard-aware-scroll-view#pull/501/head",
> ```

its not working on AppCenter builds. This PR has to be merged

**Comment by HZHAIX** [comment]
Prefer this fix to be merged ASAP, but to whom may need the fix ATM, the alternative way is using `patch-package` to generate the patch file until the owner release the new version

**Review by RatebSeirawan — APPROVED** [review]

**Comment by tonype** [comment]
Posting to also request this be merged ASAP, running into this upgrading to 0.65.

**Comment by kutaisan** [comment]
I forked repo and published with this PR at npm for AppCenter build.

https://www.npmjs.com/package/kutaisan-react-native-keyboard-aware-scroll-view

You can use this until this PR has been merged (dont forget to change, this won't be get updated)

**Comment by knro** [comment]
Please merge this whenever you can to fix the crash.

**Comment by jxom** [comment]
> Prefer this fix to be merged ASAP, but to whom may need the fix ATM, the alternative way is using patch-package to generate the patch file until the owner release the new version

Quick note – this is done by doing the following:

1. Run `yarn add patch-package -D`
2. Make the changes from this PR in your `node_modules/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js`
3. Run `yarn patch-package react-native-keyboard-aware-scroll-view` to save the patch
4. Add `"postinstall": "patch-package"` to your `package.json` to apply the saved patch on install

**Review by oularrea — APPROVED** [review]

**Comment by hsavit1** [comment]
updates?

**Comment by slorber** [comment]
I have permission to merge and publish this package, but can't dedicate time to it.

Who has used the fork, and can confirm it works for both older versions of RN + 0.65?

Merging a change that only works for the new RN version would harm the community. 

Please make sure that it's working for you (on RN 0.65) but for others too, and invest your own time to convince me it's the case with a demo app or whatever, because I can't blindly merge this PR nor invest my own time atm.

**Comment by grant273** [comment]
You should also update `KeyboardAwareScrollView.js` similarly.

**Comment by mingtsay** [comment]
> I have permission to merge and publish this package, but can't dedicate time to it.
> 
> Who has used the fork, and can confirm it works for both older versions of RN + 0.65?
> 
> Merging a change that only works for the new RN version would harm the community. What is the current RN support of current lib version? When was `scrollTo` introduced exactly?
> 
> Please make sure that it's working for you (on RN 0.65) but for others too, and invest your own time to convince me it's the case with a demo app or whatever, because I can't blindly merge this PR nor invest my own time atm.

You may want to read this comment[1] that I post before.
Also, `scrollTo` exists for a long while. At least it works in 0.48 and later.

[1] https://github.com/APSL/react-native-keyboard-aware-scroll-view/pull/501#issuecomment-919625997

**Comment by CoryWritesCode** [comment]
created a backwards compatible fix complete with newly init'ed apps referenced with the fix implemented #510

**Comment by alexbuckham** [comment]
Sometimes other dependencies within your project (for example, Native Base) will depend on an older version of the @codler fix. Add `"resolutions": { "native-base/@codler/react-native-keyboard-aware-scroll-view": "2.0.0" }` to your package.json file and run `yarn/npm install`.

**Comment by lfoliveir4** [comment]
PLEASE MERGE THIS!!!!!!!

**Comment by slorber** [comment]
This PR does not handle retrocompatibilit, closing in favor of https://github.com/APSL/react-native-keyboard-aware-scroll-view/pull/510

**Pull request closed without merging**
