### PR TITLE
Transform componentWillReceiveProps to componentDidUpdate

### PR DESCRIPTION
**Pull request by KarlosQ**
Transform componentWillReceiveProps to componentDidUpdate because componentWillReceiveProps is deprecated

### CODE REVIEW

**Comment by kimihiro64** [comment]
Can we get this in soon? After RN 60 upgrade, getting yellowbox warning for it, and I use it on every screen ;_;. @alvaromb

**Comment by smxdevst** [comment]
Please merge

**Comment by zolero** [comment]
Merge this please...

**Comment by ryardley** [comment]
If the maintainer is waiting for more testing at least use `UNSAFE_componentWillReceiveProps` to silence the warning otherwise it would be good to merge this asap.

**Comment by Cplantijn** [comment]
it'll be great to see this merged!

**Comment by morgondag** [comment]
gimmy <3

**Comment by alvaromb** [comment]
Sorry for the delay people, merged. Will release in a moment.

**Pull request merged**
